# Generated by Django 5.0.7 on 2024-11-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_customuser_full_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
