# Generated by Django 5.0.7 on 2024-11-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='guest_user',
            new_name='user',
        ),
    ]
