# Generated by Django 5.0.7 on 2024-11-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0004_rename_guest_user_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Story Comment', 'verbose_name_plural': 'Story Comments'},
        ),
    ]
